# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: literal.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'literal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rliteral.proto\"g\n\nLiteralMap\x12)\n\x07literal\x18\x01 \x03(\x0b\x32\x18.LiteralMap.LiteralEntry\x1a.\n\x0cLiteralEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'literal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LITERALMAP_LITERALENTRY']._loaded_options = None
  _globals['_LITERALMAP_LITERALENTRY']._serialized_options = b'8\001'
  _globals['_LITERALMAP']._serialized_start=17
  _globals['_LITERALMAP']._serialized_end=120
  _globals['_LITERALMAP_LITERALENTRY']._serialized_start=74
  _globals['_LITERALMAP_LITERALENTRY']._serialized_end=120
# @@protoc_insertion_point(module_scope)
